sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: FGDuhrzMYWDD1UHcmQpG9JhvxB62cnF+x0F4Lx1u94Ya+6d/80VwlOexJx37M1D2L4GxKaCGMSDBfl7UU9MK75iN4Bk/2XIYAT0yVN+itp/xyy19rnJUlhDXe2bkci7R7xbduqKpFWqHNhAv8PxLdNoqMVKG2u2vol/v/l+wnoi9d86AsdqU/aF2xRfyEw199dVeZ/jHI00+tXMAMp8lwzmGkLAZJsdrZAElTP/SNDM6rCpPG9zPzKjp7+XfjgSEb2oQfaWpJfynhWn0oIHOECzVWtcsnrNsB7T/GRVKv7DYdCzt5Ym4BbpD11+3CKvAA2kQXHnJGTq6pU5n7ZWTw93OHAKxcvfv4jctuXEGhC+mlcBwYhWFMSsOB1j8+Z3mvwLr3Hf6KjJfYNfZyDEw//0v0oZCekQgLS+pwr/OCwXVwELvCCQpxx+Drcj8ErJXAB5Q2q+E+aqI05fPwxx+ts4sBHlogB9lorGxIsMoLiG4SV98qBm0lwJ2oHQ94goNki0skQFEBVMDmCueh4A8SeC+ifXRhuF7Br+TNFltrEn3mrk8P1et3sIHjItdFFxou2AxnAELf76q+6M+/kZnbAIVCVDuzUefYgJaAmdPiatOlszGSHVLn61uKIsfkQwqCDuObbsmfGhKJWJF4JvZjHlONauSnt1mUbkFhPtEpzw=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Memoirs-of-Jacques-Casanova-de-Seingalt-1725-1798.-Volume-25--Russia-and-Poland_2975
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy